project:
  type: website
  output-dir: .

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "People"
        menu:
          - text: "Kyle P Messier"
            href: people.html#KPM
          - text: "Mariana Alifa"
            href: people.html#MAK
          - text: "Ranadeep Daw"
            href: people.html#RD
          - text: "Eva Marques"
            href: people.html#ESM
          - text: "Insang Song"
            href: people.html#IS
          - text: "Daniel Zilber"
            href: people.html#DZ
          - text: "Mitchell Manware"
            href: people.html#MM
          - text: "Former Members"
            href: people.html#FormerMembers
      - href: https://pubmed.ncbi.nlm.nih.gov/?term=Kyle+P+Messier&sort=date&format=abstract 
        text: Publications            
      - text: "Software"
        menu: 
          - text: "Software Overview"
            href: software.html
          - text: "amadeus"
            href: https://niehs.github.io/amadeus/            
          - text: "beethoven"
            href: https://niehs.github.io/beethoven/
          - text: "chopin"
            href: https://niehs.github.io/chopin/
          - text: "GeoTox" 
            href: https://niehs.github.io/GeoTox/   
          - text: "RGCA" 
            href: https://niehs.github.io/RGCA/               
          - text: "prestoGP"
            href: https://niehs.github.io/PrestoGP/
      - href: presentations.qmd 
        text: Presentations
      - about.qmd
      - href: syllabus.qmd
        text: Syllabus        
    logo: images/setlogo.jpg

format:
  html:
    theme: minty
    toc: true

editor: visual

