project:
  type: website
  output-dir: .

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "People"
        menu:
          - text: "Kyle P Messier"
            href: people.html#KPM
          - text: "Mariana Alifa"
            href: people.html#MAK
          - text: "Ranadeep Daw"
            href: people.html#RD
          - text: "Eva Marques"
            href: people.html#ESM
          - text: "Insang Song"
            href: people.html#IS
          - text: "Daniel Zilber"
            href: people.html#DZ
          - text: "Mitchell Manware"
            href: people.html#MM
          - text: "Former Members"
            href: people.html#FormerMembers            
      - text: "Software"
        menu: 
          - text: "Software Overview"
            href: software.html
          - text: "beethoven"
            href: https://kyle-messier.github.io/beethoven/
          - text: "chopin"
            href: https://kyle-messier.github.io/chopin/
          - text: "GeoTox" 
            href: https://niehs.github.io/GeoTox/              
          - text: "prestoGP"
            href: https://kyle-messier.github.io/PrestoGP/
      - text: "Publications"
        menu: 
          - text: "2024"
            href: publications/2024.html
      - text: "Presentations"
        menu: 
          - text: "NIMHD-2024-01-09"
            href: presentations/nimhd-2024-01-09.pdf
          - text: "SOT-ISES-Webinar-2024-02-14"
            href: presentations/20240214_SOT_ISES_Webinar/KPM_SOT_ISES_Webinar_20240214.html
          - text: "UNC-ENVR-500-Lecture-2024-02-22"
            href: presentations/20240222_UNC_ESE_Guest_Lecture/20240222_UNC_ESE_Guest_Lecture.html
          - text: "RENCI-Workshop-2024-02-23"
            href: presentations/20240223_CEHD_Workshop/20240223_CEHD_Workshop.html   
      - about.qmd
    logo: images/setlogo.jpg

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

