project:
  type: website
  output-dir: .

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "People"
        menu:
          - text: "Kyle P Messier"
            href: people.html#KPM
          - text: "Mariana Alifa"
            href: people.html#MAK
          - text: "Ranadeep Daw"
            href: people.html#RD
          - text: "Eva Marques"
            href: people.html#ESM
          - text: "Insang Song"
            href: people.html#IS
          - text: "Daniel Zilber"
            href: people.html#DZ
          - text: "Mitchell Manware"
            href: people.html#MM
          - text: "Former Members"
            href: people.html#FormerMembers            
      - text: "Software"
        menu: 
          - text: "Software Overview"
            href: software.html
          - text: "amadeus"
            href: https://niehs.github.io/amadeus/            
          - text: "beethoven"
            href: https://niehs.github.io/beethoven/
          - text: "chopin"
            href: https://niehs.github.io/chopin/
          - text: "GeoTox" 
            href: https://niehs.github.io/GeoTox/              
          - text: "prestoGP"
            href: https://niehs.github.io/PrestoGP/
#     - text: "Publications"
#       menu: 
#          - text: "2024"
#            href: publications/2024.html
      - href: presentations.qmd 
        text: Presentations
      - about.qmd
      - href: syllabus.qmd
        text: Syllabus        
    logo: images/setlogo.jpg

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

