project:
  type: website
  output-dir: .

website:
  title: "SET group internal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus

