project:
  type: website
  output-dir: .

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "People"
        menu:
          - text: "Kyle P Messier"
            href: people.html#KPM
          - text: "Mariana Alifa"
            href: people.html#MAK
          - text: "Eva Marques"
            href: people.html#ESM
          - text: "Mitchell Manware"
            href: people.html#MM
          - text: "Former Members"
            href: people.html#FormerMembers         
      - text: "Software"
        menu: 
          - text: "Software Overview"
            href: software.html
          - text: "amadeus"
            href: https://niehs.github.io/amadeus/            
          - text: "beethoven"
            href: https://niehs.github.io/beethoven/
          - text: "chopin"
            href: https://niehs.github.io/chopin/
          - text: "GeoTox" 
            href: https://niehs.github.io/GeoTox/   
          - text: "RGCA" 
            href: https://niehs.github.io/RGCA/               
          - text: "prestoGP"
            href: https://niehs.github.io/PrestoGP/
    logo: images/setlogo.jpg

format:
  html:
    theme: minty
    toc: true

editor: visual

