---
title: "Long-Term Exposure to Ultrafine Particles and Incidence of Cardiovascular and Cerebrovascular Disease in a Prospective Study of a Dutch Cohort"
type: "article"
author: "George S. Downward, Erik J.H.M. van Nunen, Jules Kerckhoffs, Paolo Vineis, Bert Brunekreef, Jolanda M.A. Boer, Kyle P. Messier, Ananya Roy, W. Monique M. Verschuren, Yvonne T. van der Schouw, Ivonne Sluijs, John Gulliver, Gerard Hoek, and Roel Vermeulen"
year: "2018"
publication: "Environmental Health Perspectives"
preprint: ""
doi: "https://doi.org/10.1289/EHP3047"
pmc: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6371648"
pmid: "31867444"
toc: false
categories:
  - epidemiology
  - air pollution
  - geospatial
---

## Citation

> Downward GS, van Nunen EJHM, Kerckhoffs J, Vineis P, Brunekreef B, Boer JMA, Messier KP, Roy A, Verschuren WMM, van der Schouw YT, Sluijs I, Gulliver J, Hoek G, Vermeulen R. Long-Term Exposure to Ultrafine Particles and Incidence of Cardiovascular and Cerebrovascular Disease in a Prospective Study of a Dutch Cohort. Environ Health Perspect. 2018 Dec;126(12):127007. doi: 10.1289/EHP3047. PMID: 30566375; PMCID: PMC6371648.

## Abstract

#### Background

There is growing evidence that exposure to ultrafine particles (UFP; particles smaller than 100 nm) may play an underexplored role inthe etiology of several illnesses, including cardiovascular disease (CVD)

#### Objectives

We aimed to investigate the relationship between long-term exposure to ambient UFP and incident cardiovascular and cerebrovasculardisease (CVA). As a secondary objective, we sought to compare effect estimates for UFP with those derived for other air pollutants, including esti-mates from two-pollutant models.

#### Methods

Using a prospective cohort of 33,831 Dutch residents, we studied the association between long-term exposure to UFP (predicted via land use regression) and incident disease using Cox proportional hazard models. Hazard ratios (HR) for UFP were compared to HRs for more routinely monitored air pollutants, including particulate matter with aerodynamic diameter≤10 $\mu$m (PM10), PM with aerodynamic diameter≤2.5 $\mu$m (PM2.5), and NO2.

#### Results

Long-term UFP exposure was associated with an increased risk for all incident CVD \[HR = 1:18 per 10,000 particles= $cm^3$; 95% confidence interval (CI): 1.03, 1.34\], myocardial infarction (MI) (HR = 1:34; 95% CI: 1.00, 1.79), and heart failure (HR = 1:76; 95% CI: 1.17, 2.66). Positive associations were also estimated for NO$_2$(HR for heart failure = 1:22; 95% CI: 1.01, 1.48 per 20$\mu g /m^{3}$) and coarse PM (PMcoarse; HR for all CVD = 1:21; 95% CI: 1.01, 1.45 per 10$\mu g /m^{3}$). CVD was not positively associated with PM2.5(HR for all CVD = 0:95; 95% CI: 0.75, 1.28 per 5 $\mu g /m^{3}$). HRs for UFP and CVAs were positive, but not significant. In two-pollutant models (UFP + NO2 and UFP + PMcoarse), positive associations tended to remain for UFP, while HRs for PMcoarse and NO2 generally attenuated towards the null.

#### Conclusions

These findings strengthen the evidence that UFP exposure plays an important role in cardiovascular health and that risks of ambient air pollution may have been underestimated based on conventional air pollution metrics.
