---
title: "Comparison of Ultrafine Particle and Black Carbon Concentration Predictions from a Mobile and Short-Term Stationary Land-Use Regression Model"
type: "article"
author: "Jules Kerckhoffs, Gerard Hoek, Kyle P. Messier, Bert Brunekreef, Kees Meliefste, Jochem O. Klompmaker and Roel Vermeulen"
year: "2016"
publication: "Environmental Science & Technology"
preprint: ""
doi: "https://doi.org/10.1021/acs.est.6b03476"
pmid: "27809494."
toc: false
categories:
  - air pollution
  - geospatial
---

## Citation

> Kerckhoffs J, Hoek G, Messier KP, Brunekreef B, Meliefste K, Klompmaker JO, Vermeulen R. Comparison of Ultrafine Particle and Black Carbon Concentration Predictions from a Mobile and Short-Term Stationary Land-Use Regression Model. Environ Sci Technol. 2016 Dec 6;50(23):12894-12902. doi: 10.1021/acs.est.6b03476. Epub 2016 Nov 18. PMID: 27809494.

## Abstract

Mobile and short-term monitoring campaigns are increasingly used to develop land-use regression (LUR) models for ultrafine particles (UFP) and black carbon (BC). It is not yet established whether LUR models based on mobile or short-term stationary measurements result in comparable models and concentration predictions. The goal of this paper is to compare LUR models based on stationary (30 min) and mobile UFP and BC measurements from a single campaign. An electric car collected both repeated stationary and mobile measurements in Amsterdam and Rotterdam, The Netherlands. A total of 2964 road segments and 161 stationary sites were sampled over two seasons. Our main comparison was based on predicted concentrations of the mobile and stationary monitoring LUR models at 12 682 residential addresses in Amsterdam. Predictor variables in the mobile and stationary LUR model were comparable, resulting in highly correlated predictions at external residential addresses (R2 of 0.89 for UFP and 0.88 for BC). Mobile model predictions were, on average, 1.41 and 1.91 times higher than stationary model predictions for UFP and BC, respectively. LUR models based upon mobile and stationary monitoring predicted highly correlated UFP and BC concentration surfaces, but predicted concentrations based on mobile measurements were systematically higher.
