---
title: "Associations between Flood Risk and United States Census Tract-Level Health Outcomes"
type: "article"
author: "Alvin Sheng, Brian J Reich, & Kyle P Messier"
year: "2024"
publication: "American Journal of Epidemiology (In Press)"
preprint: ""
doi: ""
pmc: ""
materials: ""
toc: false
categories:
  - mixtures
  - epidemiology
  - bayesian
  - climate
---

## Abstract

Human-induced climate change has led to more frequent and severe flooding throughout the globe. We examined the association between flood risk and the prevalence of coronary heart disease, high blood pressure, asthma, and poor mental health in the United States, while taking into account different levels of social vulnerability. We aggregated flood risk variables from First Street Foundation by census tract and used principal component analysis to derive a set of five interpretable flood risk factors. The dependent variables were census-tract level disease prevalences generated by the Centers for Disease Control and Prevention. Bayesian spatial conditional autoregressive models were fit on this data to quantify the relationship between flood risk and health outcomes under different stratifications of social vulnerability. We showed that three flood risk principal components had small but significant associations with each of the health outcomes, across the different stratifications of social vulnerability. Our analysis gives the first United States-wide estimates of the associated effects of flood risk on specific health outcomes. We also show that social vulnerability is an important moderator of the relationship between flood risk and health outcomes. Our approach can be extended to other ecological studies that examine the health impacts of climate hazards.
