---
title: "Reflected generalized concentration addition and Bayesian hierarchical models to improve chemical mixture prediction"
type: "article"
author: "Daniel Zilber & Kyle P Messier"
year: "2024"
publication: "PLOS One"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0298687"
pmc: ""
materials: ""
toc: false
categories:
  - mixtures
  - toxicology
  - bayesian
---

## Citation

> Zilber, D., & Messier, K. (2024). Reflected generalized concentration addition and Bayesian hierarchical models to improve chemical mixture prediction. Plos one, 19(3), e0298687.

## Abstract

Environmental toxicants overwhelmingly occur together as mixtures. The variety of possible chemical interactions makes it difficult to predict the danger of the mixture. In this work, we propose the novel Reflected Generalized Concentration Addition (RGCA), a piece-wise, geometric technique for sigmoidal dose-responsed inverse functions that extends the use of generalized concentration addition (GCA) for 3+ parameter models. Since experimental tests of all relevant mixtures is costly and intractable, we rely only on the individual chemical dose responses. Additionally, RGCA enhances the classical two-step model for the cumulative effects of mixtures, which assumes a combination of GCA and independent action (IA). We explore how various clustering methods can dramatically improve predictions. We compare our technique to the IA, CA, and GCA models and show in a simulation study that the two-step approach performs well under a variety of true models. We then apply our method to a challenging data set of individual chemical and mixture responses where the target is an androgen receptor (Tox21 AR-luc). Our results show significantly improved predictions for larger mixtures. Our work complements ongoing efforts to predict environmental exposure to various chemicals and offers a starting point for combining different exposure predictions to quantify a total risk to health.
